name: Deploy to Azure Container App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY_LOGIN_SERVER: papecutregisteryname.azurecr.io
  APP_NAME: papercut-backend-container
  RESOURCE_GROUP: papercut-backend-container-reg-group

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Log in to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.PAPERCUTBACKENDCONTAINER_AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.PAPERCUTBACKENDCONTAINER_AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.PAPERCUTBACKENDCONTAINER_AZURE_SUBSCRIPTION_ID }}
    
    - name: Log in to Container Registry
      run: |
        az acr login --name papecutregisteryname
        
    - name: Build and push Docker image
      run: |
        docker build -t $REGISTRY_LOGIN_SERVER/papercut-backend:${{ github.sha }} .
        docker push $REGISTRY_LOGIN_SERVER/papercut-backend:${{ github.sha }}
        
    - name: Deploy to Container App
      run: |
        az containerapp update \
          --name $APP_NAME \
          --resource-group $RESOURCE_GROUP \
          --image $REGISTRY_LOGIN_SERVER/papercut-backend:${{ github.sha }}
