name: Trigger auto deployment for papercut-backend-container
# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/papercut-backend-container-AutoDeployTrigger-5a69c023-938e-4433-8849-0d161598f4b4.yml'
  # Allow manual trigger 
  workflow_dispatch:      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.PAPERCUTBACKENDCONTAINER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PAPERCUTBACKENDCONTAINER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PAPERCUTBACKENDCONTAINER_AZURE_SUBSCRIPTION_ID }}
      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile
          registryUrl: papecutregistryname.azurecr.io
          registryUsername: ${{ secrets.REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.REGISTRY_PASSWORD }}
          containerAppName: papercut-backend-container
          resourceGroup: papercut-backend-container-reg-group
          imageToBuild: papecutregistryname.azurecr.io/papercut-backend-container:${{ github.sha }}
